// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://femobubgmnifmhiawwbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlbW9idWJnbW5pZm1oaWF3d2JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5ODI3MTUsImV4cCI6MjA2NzU1ODcxNX0.JYL914DU9aB0jc5M0ULcUNmhC6hU4OTpu_aUvolljGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});